In [2]:
import pandas as pd
import string
import nltk
from nltk.corpus import stopwords

In [3]:
df=pd.read_csv("/Users/pratiksharma/Downloads/train_data.csv")

In [4]:
df_label=pd.read_csv("/Users/pratiksharma/Downloads/train_label.csv")

In [5]:
df.head(100)

text      id
0   Keep your gloves, hats, coats and jackets toge...  122885
1   The Home Dynamix Serendipity Ivory 5 ft. 2 in....  188958
2   The Bosch 18-Volt lithium-ion line of Cordless...  146065
3   Restore your Porter-Cable sander or polisher t...  165138
4   The SPIKECUBE Surge Suppressor from Tripp Lite...  185565
..                                                ...     ...
95  Designed for jobs which require a bit more pow...  154756
96  Poma's impact resistant colonial shutter is co...  108132
97  Recycler 22 in. SmartStow High Wheel Front Whe...  118347
98  Clean mesh is effective gutter protection from...  208851
99  The Kurdamir Collection is an expansive collec...  180814

[100 rows x 2 columns]

In [6]:
df.shape

(41569, 2)

In [7]:
df_label.head(100)

id                  label
0   100003                  Shape
1   100004        Voltage (volts)
2   100004        Wattage (watts)
3   100006        Wattage (watts)
4   100007  ENERGY STAR Certified
..     ...                    ...
95  100107         Indoor/Outdoor
96  100111                  Color
97  100113  ENERGY STAR Certified
98  100113      Hardware Included
99  100114      Hardware Included

[100 rows x 2 columns]

In [8]:
df_label.shape

(75170, 2)

In [9]:
df_label.value_counts()

id      label                
181872  Shape                    2
132614  Flooring Product Type    2
191306  Flooring Product Type    2
116727  Flooring Product Type    2
130470  Flooring Product Type    2
                                ..
157917  Shape                    1
        Hardware Included        1
157914  Indoor/Outdoor           1
        ENERGY STAR Certified    1
224423  Hardware Included        1
Length: 75153, dtype: int64

In [10]:
data = pd.merge(df, df_label, on='id', how='inner')

In [11]:
data.head(100)

text      id  \
0   Keep your gloves, hats, coats and jackets toge...  122885   
1   Keep your gloves, hats, coats and jackets toge...  122885   
2   Keep your gloves, hats, coats and jackets toge...  122885   
3   The Home Dynamix Serendipity Ivory 5 ft. 2 in....  188958   
4   The Home Dynamix Serendipity Ivory 5 ft. 2 in....  188958   
..                                                ...     ...   
95  This 14 inch, 4 lb. splitting tool, is no doub...  215560   
96  These knifes are constructed with a rugged met...  122102   
97  Work in comfort with the new Work Smart new Sc...  193642   
98  The Preston design is part of the Crown Jewel ...  168041   
99  The Preston design is part of the Crown Jewel ...  168041   

                       label  
0          Assembly Required  
1                     Finish  
2          Hardware Included  
3   Commercial / Residential  
4                   Features  
..                       ...  
95        Tools Product Type  
96        Tools Product Type  
97         Assembly Required  
98                  Features  
99                  Included  

[100 rows x 3 columns]

In [12]:
data.shape

(75170, 3)

In [13]:
# Remove duplicate rows based on 'text' and 'id' columns
data_new = data.drop_duplicates(subset=['text', 'id'])

In [14]:
data_new.head()

text      id  \
0   Keep your gloves, hats, coats and jackets toge...  122885   
3   The Home Dynamix Serendipity Ivory 5 ft. 2 in....  188958   
7   The Bosch 18-Volt lithium-ion line of Cordless...  146065   
9   Restore your Porter-Cable sander or polisher t...  165138   
10  The SPIKECUBE Surge Suppressor from Tripp Lite...  185565   

                       label  
0          Assembly Required  
3   Commercial / Residential  
7         Tools Product Type  
9         Tools Product Type  
10  Commercial / Residential

In [15]:
aggregated_data = data.groupby('id').agg({'text': 'first', 'label': list}).reset_index()

In [16]:
aggregated_data.head(100)

id                                               text  \
0   100003  Classic architecture meets contemporary design...   
1   100004  The Grape Solar 265-Watt Polycrystalline PV So...   
2   100006  Achieving delicious results is almost effortle...   
3   100007  The Quantum Adjustable 2-Light LED Black Emerg...   
4   100008  The Teks #10 x 1-1/2 in. Zinc-Plated Steel Was...   
..     ...                                                ...   
95  100189  With four more inches in depth added to the st...   
96  100190  This Freeport Pure White 3-Shelf Bookcase is I...   
97  100192  Since 1910, General Tools has grown to become ...   
98  100193  36 in. x 80 in. wood mahogany prehung 2-panel ...   
99  100194  DEWALT delivers huge value with this two-pack,...   

                                             label  
0                                          [Shape]  
1               [Voltage (volts), Wattage (watts)]  
2                                [Wattage (watts)]  
3                          [ENERGY STAR Certified]  
4       [Finish, Indoor/Outdoor, Package Quantity]  
..                                             ...  
95  [Assembly Required, Finish, Hardware Included]  
96  [Assembly Required, Finish, Hardware Included]  
97                                         [Shape]  
98                            [Features, Included]  
99           [Tools Product Type, Voltage (volts)]  

[100 rows x 3 columns]

In [17]:
aggregated_data.shape


(41569, 3)

In [18]:
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/pratiksharma/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [21]:
aggregated_data['tokenized_text'] = aggregated_data['text'].apply(lambda x: word_tokenize(x))

In [22]:
print(aggregated_data[['text', 'tokenized_text']])

                                                    text  \
0      Classic architecture meets contemporary design...   
1      The Grape Solar 265-Watt Polycrystalline PV So...   
2      Achieving delicious results is almost effortle...   
3      The Quantum Adjustable 2-Light LED Black Emerg...   
4      The Teks #10 x 1-1/2 in. Zinc-Plated Steel Was...   
...                                                  ...   
41564  The Clearflo Brass Toe-tap bath drain works pe...   
41565  Paracord is ideal for camping, hiking and othe...   
41566  Wheel Chair Accessible's provide a safe and in...   
41567  These wood screws are thread forming screws wi...   
41568  The Legend Series framed swing stand-alone con...   

                                          tokenized_text  
0      [Classic, architecture, meets, contemporary, d...  
1      [The, Grape, Solar, 265-Watt, Polycrystalline,...  
2      [Achieving, delicious, results, is, almost, ef...  
3      [The, Quantum, Adjustable, 2-Light, 

In [21]:
import re

def preprocess_tokens(tokens_list):
    cleaned_tokens = [re.sub(r'[^a-zA-Z]', '', str(token)) for token in tokens_list]
    return cleaned_tokens

In [22]:
aggregated_data['cleaned_tokens'] = preprocess_tokens(aggregated_data['tokenized_text'])

In [25]:

aggregated_data['cleaned_tokens']

0        Classicarchitecturemeetscontemporarydesigninth...
1        TheGrapeSolarWattPolycrystallinePVSolarPanelbo...
2        Achievingdeliciousresultsisalmosteffortlesswit...
3        TheQuantumAdjustableLightLEDBlackEmergencyLigh...
4        TheTeksxinZincPlatedSteelWasherHeadHexSelfTapp...
                               ...                        
41564    TheClearfloBrassToetapbathdrainworksperfectlyi...
41565    Paracordisidealforcampinghikingandotheroutdoor...
41566    WheelChairAccessiblesprovideasafeandindependen...
41567    Thesewoodscrewsarethreadformingscrewswithlarge...
41568    TheLegendSeriesframedswingstandalonecontinuous...
Name: cleaned_tokens, Length: 41569, dtype: object

## Small Case 

In [23]:
aggregated_data['cleaned_tokens'] = [ [word.lower() for word in words] for words in aggregated_data['tokenized_text'] ]


In [24]:
aggregated_data['cleaned_tokens']

0        [classic, architecture, meets, contemporary, d...
1        [the, grape, solar, 265-watt, polycrystalline,...
2        [achieving, delicious, results, is, almost, ef...
3        [the, quantum, adjustable, 2-light, led, black...
4        [the, teks, #, 10, x, 1-1/2, in, ., zinc-plate...
                               ...                        
41564    [the, clearflo, brass, toe-tap, bath, drain, w...
41565    [paracord, is, ideal, for, camping, ,, hiking,...
41566    [wheel, chair, accessible, 's, provide, a, saf...
41567    [these, wood, screws, are, thread, forming, sc...
41568    [the, legend, series, framed, swing, stand-alo...
Name: cleaned_tokens, Length: 41569, dtype: object

In [25]:
from nltk.corpus import stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/pratiksharma/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

## Stop Words Removal

In [26]:
def remove_stopwords(text):
    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in text if word.lower() not in stop_words]
    return ' '.join(filtered_tokens)


In [27]:
aggregated_data['cleaned_tokens'] = aggregated_data['cleaned_tokens'].apply(remove_stopwords)


In [28]:
aggregated_data['cleaned_tokens']

0        classic architecture meets contemporary design...
1        grape solar 265-watt polycrystalline pv solar ...
2        achieving delicious results almost effortless ...
3        quantum adjustable 2-light led black emergency...
4        teks # 10 x 1-1/2 . zinc-plated steel washer-h...
                               ...                        
41564    clearflo brass toe-tap bath drain works perfec...
41565    paracord ideal camping , hiking outdoor activi...
41566    wheel chair accessible 's provide safe indepen...
41567    wood screws thread forming screws larger threa...
41568    legend series framed swing stand-alone continu...
Name: cleaned_tokens, Length: 41569, dtype: object

## Stemming

In [29]:
from nltk.stem import PorterStemmer

stemmer = PorterStemmer()

In [30]:
def stem_tokens(tokens):
    return [stemmer.stem(token) for token in tokens]

In [31]:
aggregated_data['stemmed_tokens'] = aggregated_data['cleaned_tokens'].apply(stem_tokens)

In [32]:
aggregated_data['stemmed_tokens']

0        [c, l, a, s, s, i, c,  , a, r, c, h, i, t, e, ...
1        [g, r, a, p, e,  , s, o, l, a, r,  , 2, 6, 5, ...
2        [a, c, h, i, e, v, i, n, g,  , d, e, l, i, c, ...
3        [q, u, a, n, t, u, m,  , a, d, j, u, s, t, a, ...
4        [t, e, k, s,  , #,  , 1, 0,  , x,  , 1, -, 1, ...
                               ...                        
41564    [c, l, e, a, r, f, l, o,  , b, r, a, s, s,  , ...
41565    [p, a, r, a, c, o, r, d,  , i, d, e, a, l,  , ...
41566    [w, h, e, e, l,  , c, h, a, i, r,  , a, c, c, ...
41567    [w, o, o, d,  , s, c, r, e, w, s,  , t, h, r, ...
41568    [l, e, g, e, n, d,  , s, e, r, i, e, s,  , f, ...
Name: stemmed_tokens, Length: 41569, dtype: object

In [33]:
# Convert tokenized documents to list of strings
aggregated_data['tokenized_docs_as_strings'] = [' '.join(tokens) for tokens in aggregated_data['stemmed_tokens']]

In [34]:
aggregated_data['tokenized_docs_as_strings']

0        c l a s s i c   a r c h i t e c t u r e   m e ...
1        g r a p e   s o l a r   2 6 5 - w a t t   p o ...
2        a c h i e v i n g   d e l i c i o u s   r e s ...
3        q u a n t u m   a d j u s t a b l e   2 - l i ...
4        t e k s   #   1 0   x   1 - 1 / 2   .   z i n ...
                               ...                        
41564    c l e a r f l o   b r a s s   t o e - t a p   ...
41565    p a r a c o r d   i d e a l   c a m p i n g   ...
41566    w h e e l   c h a i r   a c c e s s i b l e   ...
41567    w o o d   s c r e w s   t h r e a d   f o r m ...
41568    l e g e n d   s e r i e s   f r a m e d   s w ...
Name: tokenized_docs_as_strings, Length: 41569, dtype: object

In [35]:
tokenized_docs_as_strings = aggregated_data['tokenized_docs_as_strings']

In [36]:
tokenized_docs_as_strings 

0        c l a s s i c   a r c h i t e c t u r e   m e ...
1        g r a p e   s o l a r   2 6 5 - w a t t   p o ...
2        a c h i e v i n g   d e l i c i o u s   r e s ...
3        q u a n t u m   a d j u s t a b l e   2 - l i ...
4        t e k s   #   1 0   x   1 - 1 / 2   .   z i n ...
                               ...                        
41564    c l e a r f l o   b r a s s   t o e - t a p   ...
41565    p a r a c o r d   i d e a l   c a m p i n g   ...
41566    w h e e l   c h a i r   a c c e s s i b l e   ...
41567    w o o d   s c r e w s   t h r e a d   f o r m ...
41568    l e g e n d   s e r i e s   f r a m e d   s w ...
Name: tokenized_docs_as_strings, Length: 41569, dtype: object

# Lemmatization

In [36]:
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet

nltk.download('wordnet')
nltk.download('omw-1.4')
# Initialize lemmatizer
lemmatizer = WordNetLemmatizer()

# Lemmatize the tokens in the 'cleaned_tokens' column
aggregated_data['lemmatized_tokens'] = aggregated_data['cleaned_tokens'].apply(
    lambda tokens: [lemmatizer.lemmatize(token, pos=wordnet.VERB) for token in tokens]
)

[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/pratiksharma/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     /Users/pratiksharma/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


In [37]:
print(aggregated_data[['cleaned_tokens', 'lemmatized_tokens']])

                                          cleaned_tokens  \
0      classic architecture meets contemporary design...   
1      grape solar 265-watt polycrystalline pv solar ...   
2      achieving delicious results almost effortless ...   
3      quantum adjustable 2-light led black emergency...   
4      teks # 10 x 1-1/2 . zinc-plated steel washer-h...   
...                                                  ...   
41564  clearflo brass toe-tap bath drain works perfec...   
41565  paracord ideal camping , hiking outdoor activi...   
41566  wheel chair accessible 's provide safe indepen...   
41567  wood screws thread forming screws larger threa...   
41568  legend series framed swing stand-alone continu...   

                                       lemmatized_tokens  
0      [c, l, a, s, s, i, c,  , a, r, c, h, i, t, e, ...  
1      [g, r, a, p, e,  , s, o, l, a, r,  , 2, 6, 5, ...  
2      [a, c, h, i, e, v, i, n, g,  , d, e, l, i, c, ...  
3      [q, u, a, n, t, u, m,  , a, d, j, u,

In [38]:
aggregated_data['lemmatized_docs_as_strings'] = [' '.join(tokens) for tokens in aggregated_data['lemmatized_tokens']]

In [39]:
aggregated_data['lemmatized_docs_as_strings']

0        c l a s s i c   a r c h i t e c t u r e   m e ...
1        g r a p e   s o l a r   2 6 5 - w a t t   p o ...
2        a c h i e v i n g   d e l i c i o u s   r e s ...
3        q u a n t u m   a d j u s t a b l e   2 - l i ...
4        t e k s   #   1 0   x   1 - 1 / 2   .   z i n ...
                               ...                        
41564    c l e a r f l o   b r a s s   t o e - t a p   ...
41565    p a r a c o r d   i d e a l   c a m p i n g   ...
41566    w h e e l   c h a i r   a c c e s s i b l e   ...
41567    w o o d   s c r e w s   t h r e a d   f o r m ...
41568    l e g e n d   s e r i e s   f r a m e d   s w ...
Name: lemmatized_docs_as_strings, Length: 41569, dtype: object

## CountVectorizer

In [29]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(aggregated_data['cleaned_tokens'])

In [30]:
X.shape

(41569, 137841)

In [31]:
# Convert the sparse matrix to an array
count_matrix = X.toarray()


In [32]:
count_matrix

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [33]:
count_matrix.shape

(41569, 137841)

In [34]:
vocab = vectorizer.get_feature_names_out()

# Print the count matrix and vocabulary
print("Count Matrix:")
print(count_matrix)
print("\nVocabulary:")
print(vocab)

Count Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Vocabulary:
['00' '000' '0000' ... 'zurn' 'zwipes' 'zxe']


In [35]:
vectorizer.vocabulary_

{'classic': 25868,
 'architecture': 12484,
 'meets': 80064,
 'contemporary': 31284,
 'design': 37843,
 'ensemble': 46674,
 'curve': 34689,
 'series': 109223,
 'made': 77873,
 'solid': 113444,
 'vikrell': 131749,
 'material': 79121,
 'blending': 18011,
 'sleek': 112479,
 'clean': 25919,
 'lines': 75100,
 'gentle': 56027,
 'curves': 34693,
 'corner': 32962,
 'shelving': 110764,
 'perfect': 91548,
 'storing': 117838,
 'bath': 15830,
 'accessories': 7952,
 'modular': 81794,
 'allows': 10080,
 'moved': 83126,
 'around': 13049,
 'corners': 32978,
 'doorways': 41270,
 'ease': 44148,
 'wall': 132533,
 'smooth': 112959,
 'look': 76685,
 'featuring': 49609,
 'integrated': 68547,
 'storage': 117466,
 'shelves': 110633,
 'slightly': 112647,
 'narrower': 83860,
 'tighter': 124036,
 'spacesdesigned': 114136,
 '18': 1666,
 'aprondurable': 12366,
 'high': 61169,
 'gloss': 56668,
 'finish': 50491,
 'provides': 97787,
 'shiny': 110913,
 'surface': 119860,
 'easy': 44433,
 'cleanconforms': 25967,
 'ansi'

## TF-IDF Metrics

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer


# Create an instance of TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer(analyzer='word', max_features=1000)

# Fit and transform the documents to TF-IDF vectors
x = tfidf_vectorizer.fit_transform(aggregated_data['cleaned_tokens'])



In [37]:
x

<41569x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1800523 stored elements in Compressed Sparse Row format>

In [38]:
tfidf_vectorizer.vocabulary_

{'classic': 172,
 'meets': 573,
 'contemporary': 214,
 'design': 263,
 'series': 795,
 'made': 549,
 'solid': 832,
 'material': 564,
 'sleek': 819,
 'clean': 173,
 'lines': 533,
 'corner': 229,
 'perfect': 660,
 'bath': 99,
 'accessories': 39,
 'allows': 60,
 'around': 77,
 'ease': 298,
 'wall': 960,
 'smooth': 826,
 'look': 543,
 'featuring': 352,
 'integrated': 487,
 'storage': 857,
 'shelves': 806,
 'slightly': 822,
 '18': 11,
 'high': 444,
 'gloss': 411,
 'finish': 359,
 'provides': 709,
 'surface': 872,
 'easy': 301,
 'ansi': 68,
 'csa': 240,
 'solar': 830,
 'watt': 968,
 'panel': 650,
 'pack': 645,
 'panels': 651,
 'extra': 339,
 'uses': 939,
 'efficiency': 304,
 'quality': 718,
 'long': 541,
 'output': 640,
 'virtually': 955,
 'maintenance': 551,
 'free': 385,
 'low': 545,
 'iron': 490,
 'tempered': 886,
 'glass': 410,
 'durability': 294,
 'impact': 464,
 'resistance': 754,
 'power': 683,
 'reduces': 737,
 'dirt': 277,
 'performance': 661,
 'light': 526,
 'withstand': 987,
 'sno

In [39]:
x.shape, y.shape

NameError: name 'y' is not defined

In [40]:
# Convert the TF-IDF matrix to an array (for easier viewing)
tfidf_array = x.toarray()

# Get the vocabulary (list of words in the TF-IDF representation)
vocabulary = tfidf_vectorizer.get_feature_names_out()

# Print the TF-IDF representation
print("TF-IDF Representation:")
print(vocabulary)
print(tfidf_array)


TF-IDF Representation:
['000' '10' '100' '11' '12' '120' '13' '14' '15' '16' '17' '18' '20' '200'
 '21' '22' '23' '24' '25' '28' '30' '32' '35' '36' '40' '45' '48' '50'
 '500' '60' '65' '72' '75' '80' '90' 'abrasion' 'absorption' 'accent'
 'access' 'accessories' 'accommodate' 'account' 'accurate' 'acrylic'
 'actual' 'add' 'added' 'adding' 'addition' 'additional' 'adds' 'adhesive'
 'adjust' 'adjustable' 'advanced' 'air' 'alarm' 'all' 'allow' 'allowing'
 'allows' 'along' 'also' 'aluminum' 'american' 'amp' 'ample' 'angle'
 'ansi' 'antique' 'anywhere' 'appearance' 'appliances' 'application'
 'applications' 'area' 'areas' 'around' 'arrive' 'art' 'assemble'
 'assembled' 'assembly' 'attached' 'attractive' 'auto' 'automatically'
 'available' 'away' 'back' 'backed' 'backerboard' 'backing' 'bag' 'ball'
 'bar' 'base' 'based' 'basic' 'bath' 'bathroom' 'bathrooms' 'batteries'
 'battery' 'bay' 'bearing' 'beautiful' 'beauty' 'bed' 'best' 'better' 'bi'
 'bit' 'bits' 'black' 'blade' 'blades' 'blend' 'b

In [41]:
print(vocabulary)

['000' '10' '100' '11' '12' '120' '13' '14' '15' '16' '17' '18' '20' '200'
 '21' '22' '23' '24' '25' '28' '30' '32' '35' '36' '40' '45' '48' '50'
 '500' '60' '65' '72' '75' '80' '90' 'abrasion' 'absorption' 'accent'
 'access' 'accessories' 'accommodate' 'account' 'accurate' 'acrylic'
 'actual' 'add' 'added' 'adding' 'addition' 'additional' 'adds' 'adhesive'
 'adjust' 'adjustable' 'advanced' 'air' 'alarm' 'all' 'allow' 'allowing'
 'allows' 'along' 'also' 'aluminum' 'american' 'amp' 'ample' 'angle'
 'ansi' 'antique' 'anywhere' 'appearance' 'appliances' 'application'
 'applications' 'area' 'areas' 'around' 'arrive' 'art' 'assemble'
 'assembled' 'assembly' 'attached' 'attractive' 'auto' 'automatically'
 'available' 'away' 'back' 'backed' 'backerboard' 'backing' 'bag' 'ball'
 'bar' 'base' 'based' 'basic' 'bath' 'bathroom' 'bathrooms' 'batteries'
 'battery' 'bay' 'bearing' 'beautiful' 'beauty' 'bed' 'best' 'better' 'bi'
 'bit' 'bits' 'black' 'blade' 'blades' 'blend' 'block' 'blue' 'body'
 'b

In [42]:
from sklearn.preprocessing import MultiLabelBinarizer

In [43]:
y=aggregated_data['label']


In [44]:
y

0                                                  [Shape]
1                       [Voltage (volts), Wattage (watts)]
2                                        [Wattage (watts)]
3                                  [ENERGY STAR Certified]
4               [Finish, Indoor/Outdoor, Package Quantity]
                               ...                        
41564                                             [Finish]
41565                                   [Package Quantity]
41566    [Included, Shape, Voltage (volts), Wattage (wa...
41567           [Finish, Indoor/Outdoor, Package Quantity]
41568                                  [Hardware Included]
Name: label, Length: 41569, dtype: object

## Using MultilabelBinarizer

In [45]:
multilabel = MultiLabelBinarizer()

In [46]:
ym = multilabel.fit_transform(aggregated_data['label'])

In [47]:
ym

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 1, 1],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [48]:
multilabel.classes_

array(['Assembly Required', 'Color', 'Commercial / Residential',
       'ENERGY STAR Certified', 'Features', 'Finish',
       'Flooring Product Type', 'Hardware Included', 'Included',
       'Indoor/Outdoor', 'Package Quantity', 'Shape',
       'Tools Product Type', 'Voltage (volts)', 'Wattage (watts)'],
      dtype=object)

In [49]:
pd.DataFrame(ym, columns=multilabel.classes_)

Assembly Required  Color  Commercial / Residential  \
0                      0      0                         0   
1                      0      0                         0   
2                      0      0                         0   
3                      0      0                         0   
4                      0      0                         0   
...                  ...    ...                       ...   
41564                  0      0                         0   
41565                  0      0                         0   
41566                  0      0                         0   
41567                  0      0                         0   
41568                  0      0                         0   

       ENERGY STAR Certified  Features  Finish  Flooring Product Type  \
0                          0         0       0                      0   
1                          0         0       0                      0   
2                          0         0       0                      0   
3                          1         0       0                      0   
4                          0         0       1                      0   
...                      ...       ...     ...                    ...   
41564                      0         0       1                      0   
41565                      0         0       0                      0   
41566                      0         0       0                      0   
41567                      0         0       1                      0   
41568                      0         0       0                      0   

       Hardware Included  Included  Indoor/Outdoor  Package Quantity  Shape  \
0                      0         0               0                 0      1   
1                      0         0               0                 0      0   
2                      0         0               0                 0      0   
3                      0         0               0                 0      0   
4                      0         0               1                 1      0   
...                  ...       ...             ...               ...    ...   
41564                  0         0               0                 0      0   
41565                  0         0               0                 1      0   
41566                  0         1               0                 0      1   
41567                  0         0               1                 1      0   
41568                  1         0               0                 0      0   

       Tools Product Type  Voltage (volts)  Wattage (watts)  
0                       0                0                0  
1                       0                1                1  
2                       0                0                1  
3                       0                0                0  
4                       0                0                0  
...                   ...              ...              ...  
41564                   0                0                0  
41565                   0                0                0  
41566                   0                1                1  
41567                   0                0                0  
41568                   0                0                0  

[41569 rows x 15 columns]

In [45]:
from sklearn.model_selection import train_test_split

In [46]:
x_train, x_test, ym_train, ym_test = train_test_split(x ,ym, test_size=0.2, random_state=0)

In [65]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import classification_report

lr = LogisticRegression(solver='lbfgs')
svc = LinearSVC()

In [66]:
for classifier in [lr, svc]:
    clf = OneVsRestClassifier(classifier)
    clf.fit(x_train, ym_train)
    y_pred = clf.predict(x_test)
    

In [68]:
report = classification_report(ym_test, y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.88      0.76      0.81       832
           1       0.76      0.51      0.61       907
           2       0.91      0.81      0.86      1404
           3       0.92      0.85      0.88      1298
           4       0.93      0.86      0.89       807
           5       0.85      0.73      0.79       728
           6       0.98      0.94      0.96       882
           7       0.79      0.62      0.70      1137
           8       0.85      0.70      0.76       903
           9       0.81      0.76      0.79      1942
          10       0.86      0.74      0.80      1021
          11       0.80      0.62      0.70       675
          12       0.92      0.87      0.89       901
          13       0.87      0.77      0.81       929
          14       0.84      0.76      0.80       793

   micro avg       0.87      0.76      0.81     15159
   macro avg       0.86      0.75      0.80     15159
weighted avg       0.86   

/Users/pratiksharma/opt1/anaconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [70]:
from sklearn.metrics import hamming_loss
hamming_loss_value = hamming_loss(ym_test, y_pred)
print("Hamming Loss:", hamming_loss_value)

Hamming Loss: 0.0436292197899126


In [71]:
from sklearn.metrics import accuracy_score
exact_match_ratio = accuracy_score(ym_test, y_pred)
print("Exact Match Ratio:", exact_match_ratio)

Exact Match Ratio: 0.5744527303343757


In [72]:
from sklearn.metrics import jaccard_score
jaccard_similarity = jaccard_score(ym_test, y_pred, average='samples')
print("Jaccard Similarity:", jaccard_similarity)

Jaccard Similarity: 0.6980133910672761


# Without Using Multilabel Binarizer

## Naive Bayes

In [51]:
from sklearn.model_selection import train_test_split

## Count Vectorizer 

In [50]:
X_train, X_test, ym_train, ym_test = train_test_split(X ,ym, test_size=0.2, random_state=0)

In [51]:
X_train.shape

(33255, 137841)

In [55]:
pip install scikit-multilearn

Note: you may need to restart the kernel to use updated packages.


In [53]:
import numpy as np
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Assuming you have the CountVectorizer matrix named 'X_count' and labels named 'y'


# Create a Multinomial Naive Bayes classifier
classifier = BinaryRelevance(classifier=MultinomialNB(), require_dense=[False, True])




In [54]:
# converting labels into 1d array
# ym_train_1d = ym_train.flatten() # or ym_train.ravel()

# Train the classifier
classifier.fit(X_train, ym_train)



BinaryRelevance(classifier=MultinomialNB(), require_dense=[False, True])

In [55]:
# Make predictions on new data
new_data_count = X_test  # Your new data as CountVectorizer matrix
predicted_count = classifier.predict(new_data_count)



In [56]:
# Evaluate the model
accuracy = accuracy_score(ym_test, predicted_count)

In [57]:
print("accuracy=", accuracy)

accuracy= 0.5722877074813567


In [58]:
from sklearn.metrics import classification_report

report = classification_report(ym_test, predicted_count)
print(report)

              precision    recall  f1-score   support

           0       0.74      0.88      0.80       832
           1       0.79      0.71      0.75       907
           2       0.93      0.80      0.86      1404
           3       0.82      0.93      0.87      1298
           4       0.89      0.93      0.91       807
           5       0.78      0.87      0.82       728
           6       0.97      0.95      0.96       882
           7       0.70      0.82      0.75      1137
           8       0.78      0.84      0.81       903
           9       0.83      0.85      0.84      1942
          10       0.85      0.81      0.83      1021
          11       0.76      0.74      0.75       675
          12       0.82      0.96      0.88       901
          13       0.66      0.92      0.77       929
          14       0.65      0.90      0.76       793

   micro avg       0.79      0.86      0.83     15159
   macro avg       0.80      0.86      0.82     15159
weighted avg       0.80   

/Users/pratiksharma/opt1/anaconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [83]:
from sklearn.metrics import hamming_loss
hamming_loss_value = hamming_loss(ym_test, predicted_count)
print("Hamming Loss:", hamming_loss_value)

Hamming Loss: 0.04399005693208243


In [84]:
from sklearn.metrics import accuracy_score
exact_match_ratio = accuracy_score(ym_test, predicted_count)
print("Exact Match Ratio:", exact_match_ratio)

Exact Match Ratio: 0.5722877074813567


In [85]:
from sklearn.metrics import jaccard_score
jaccard_similarity = jaccard_score(ym_test,predicted_count, average='samples')
print("Jaccard Similarity:", jaccard_similarity)

Jaccard Similarity: 0.7418793909562493


## BY using TF-IDF Metrics

In [52]:
x_train, x_test, ym_train, ym_test = train_test_split(x ,ym, test_size=0.2, random_state=0)

In [54]:
x_train.shape, ym_train.shape

((33255, 1000), (33255, 15))

In [56]:
import numpy as np
from skmultilearn.problem_transform import BinaryRelevance
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# Assuming you have the CountVectorizer matrix named 'X_count' and labels named 'y'


# Create a Multinomial Naive Bayes classifier
classifierTF = BinaryRelevance(classifier=MultinomialNB(), require_dense=[False, True])




In [57]:
classifierTF.fit(x_train,ym_train)

BinaryRelevance(classifier=MultinomialNB(), require_dense=[False, True])

In [60]:
# Make predictions on new data
new_data_countTF = x_test  # Your new data as CountVectorizer matrix
predicted_countTF = classifierTF.predict(new_data_countTF)



In [62]:
# Evaluate the model
accuracyTF = accuracy_score(ym_test, predicted_countTF)

In [64]:
print("accuracy=", accuracyTF)

accuracy= 0.3241520327159009


In [65]:
from sklearn.metrics import classification_report

report = classification_report(ym_test, predicted_countTF)
print(report)

              precision    recall  f1-score   support

           0       0.83      0.54      0.65       832
           1       0.75      0.17      0.27       907
           2       0.96      0.52      0.68      1404
           3       0.85      0.74      0.79      1298
           4       0.98      0.47      0.64       807
           5       0.81      0.50      0.62       728
           6       0.99      0.82      0.90       882
           7       0.74      0.39      0.51      1137
           8       0.92      0.29      0.44       903
           9       0.82      0.44      0.57      1942
          10       0.94      0.52      0.67      1021
          11       0.93      0.25      0.40       675
          12       0.85      0.72      0.78       901
          13       0.74      0.67      0.70       929
          14       0.68      0.58      0.63       793

   micro avg       0.85      0.51      0.64     15159
   macro avg       0.85      0.51      0.62     15159
weighted avg       0.85   

/Users/pratiksharma/opt1/anaconda3/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [66]:
from sklearn.metrics import hamming_loss
hamming_loss_value = hamming_loss(ym_test, predicted_countTF)
print("Hamming Loss:", hamming_loss_value)

Hamming Loss: 0.07056370780210088


In [67]:
from sklearn.metrics import accuracy_score
exact_match_ratio = accuracy_score(ym_test, predicted_countTF)
print("Exact Match Ratio:", exact_match_ratio)

Exact Match Ratio: 0.3241520327159009


In [68]:
from sklearn.metrics import jaccard_score
jaccard_similarity = jaccard_score(ym_test,predicted_countTF, average='samples')
print("Jaccard Similarity:", jaccard_similarity)

Jaccard Similarity: 0.4506134231416887
